# src/utils/email_notifier.py
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import threading
from src.utils.logger import setup_logger

logger = setup_logger("Email_Engine")

# ⚙️ EMAIL CONFIGURATION
SENDER_EMAIL = "louaycherif6@gmail.com"  
# 👇 Your generated Google App Password (spaces removed)
APP_PASSWORD = "bihexnftxafadbep" 
RECEIVER_EMAIL = "louaycherif6@gmail.com" # The Admin email receiving the alerts

def send_violation_alert(node_id, plate_number, v_type, speed, fine, image_url):
    """Sends a professional HTML email alert to the system admin."""
    
    subject = f"🚨 SMART CITY ALERT: {v_type.replace('_', ' ')} Detected at {node_id}"
    
    # 🎨 Professional HTML Email Template
    html_content = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 10px; overflow: hidden;">
        <div style="background-color: #002b5c; padding: 20px; text-align: center;">
            <h1 style="color: #fff; margin: 0; font-style: italic;">CAPGEMINI</h1>
            <p style="color: #00a0d1; margin: 5px 0 0 0; font-size: 12px; letter-spacing: 2px;">SMART CITY ADAS PLATFORM</p>
        </div>
        <div style="padding: 30px; background-color: #f9fbfd;">
            <h2 style="color: #d9534f; border-bottom: 2px solid #d9534f; padding-bottom: 10px;">Incident Report</h2>
            <p><strong>Node Location:</strong> {node_id}</p>
            <p><strong>Violation Type:</strong> {v_type.replace('_', ' ')}</p>
            <p><strong>License Plate:</strong> <span style="font-family: monospace; font-size: 16px; background: #eee; padding: 4px 8px; border-radius: 4px;">{plate_number}</span></p>
            <p><strong>Recorded Speed:</strong> {speed} km/h</p>
            <p><strong>Calculated Fine:</strong> <span style="color: #002b5c; font-weight: bold;">{fine} TND</span></p>
            
            <div style="text-align: center; margin-top: 30px;">
                <a href="{image_url}" style="background-color: #00a0d1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">View Evidence Image</a>
            </div>
        </div>
        <div style="background-color: #eee; padding: 15px; text-align: center; font-size: 10px; color: #777;">
            <p>This is an automated message generated by the Capgemini Distributed Edge Network.</p>
        </div>
      </body>
    </html>
    """

    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = subject
    msg.attach(MIMEText(html_content, 'html'))

    try:
        # Connect to Gmail's SMTP server
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(SENDER_EMAIL, APP_PASSWORD)
        server.send_message(msg)
        server.quit()
        logger.info(f"✉️ Alert email successfully sent to {RECEIVER_EMAIL} for plate {plate_number}")
    except Exception as e:
        logger.error(f"❌ Failed to send email alert: {e}")