# src/decision/predictive_ml.py
import sqlite3
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import joblib
import os
from src.utils.logger import setup_logger

logger = setup_logger("PredictiveML")

def train_congestion_model(db_path="traffic_system.db", model_dir="models"):
    logger.info("🧠 Fetching historical traffic data from SQLite...")
    
    try:
        conn = sqlite3.connect(db_path)
        # Read the historical data generated by your system
        df = pd.read_sql_query("SELECT * FROM traffic_metrics", conn)
        conn.close()
    except Exception as e:
        logger.error(f"❌ Failed to read database: {e}")
        return

    # Ensure we have enough data to actually train an AI
    if len(df) < 50:
        logger.warning(f"⚠️ Only found {len(df)} records. Not enough data to train the AI! Let the system run longer.")
        return

    logger.info(f"📊 Found {len(df)} traffic records. Engineering features...")

    # --- 1. FEATURE ENGINEERING ---
    # Machine Learning models cannot read raw string timestamps, so we break them down into math.
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    
    # Traffic is heavily dependent on the time of day and the day of the week
    df['hour'] = df['timestamp'].dt.hour
    df['minute'] = df['timestamp'].dt.minute
    df['day_of_week'] = df['timestamp'].dt.dayofweek

    # Define our inputs (X) and what we want to predict (y)
    # We feed it the time, the volume of cars, and the average speed
    X = df[['hour', 'minute', 'day_of_week', 'vehicle_count', 'avg_speed']]
    y = df['congestion_level']

    # Split the data: 80% to train the AI, 20% to test it like an exam
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # --- 2. MODEL TRAINING ---
    logger.info("⚙️ Training Random Forest AI Model...")
    # Random Forest is highly resilient to overfitting and runs very fast on Edge CPU hardware
    model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)

    # --- 3. MODEL EVALUATION ---
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    logger.info(f"🎯 Model trained successfully! Accuracy: {accuracy * 100:.2f}%")
    
    # Optional: Print detailed metrics (Precision, Recall, F1-Score) to terminal for your defense
    print("\n--- AI Classification Report ---")
    print(classification_report(y_test, predictions, zero_division=0))
    print("--------------------------------\n")

    # --- 4. EXPORT MODEL ---
    os.makedirs(model_dir, exist_ok=True)
    model_path = os.path.join(model_dir, "congestion_model.pkl")
    
    # Save the trained AI brain to disk so FastAPI can load it later
    joblib.dump(model, model_path)
    logger.info(f"💾 Trained AI model securely saved to {model_path}")

if __name__ == "__main__":
    train_congestion_model()